"""6

Revision ID: 99d725b53695
Revises: 74af2b5d7b17
Create Date: 2023-12-26 02:50:33.411212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d725b53695'
down_revision: Union[str, None] = '74af2b5d7b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('business', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'business', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'business', type_='foreignkey')
    op.drop_column('business', 'address_id')
    op.drop_table('address')
    # ### end Alembic commands ###
