"""12

Revision ID: 9a548c0df379
Revises: a7849f5804d5
Create Date: 2023-12-26 22:13:33.741009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a548c0df379'
down_revision: Union[str, None] = 'a7849f5804d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('business', sa.Column('city', sa.String(length=50), nullable=False))
    op.add_column('business', sa.Column('address', sa.String(length=100), nullable=False))
    op.drop_constraint('business_address_id_fkey', 'business', type_='foreignkey')
    op.drop_column('business', 'address_id')
    op.drop_table('address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('business_address_id_fkey', 'business', 'address', ['address_id'], ['id'])
    op.drop_column('business', 'address')
    op.drop_column('business', 'city')
    op.drop_column('business', 'country')
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='address_pkey')
    )
    # ### end Alembic commands ###
